import { experience } from "../props";
export const ExperienceValues: experience[] = [
  {
    domain: "Mechanical Engineering",
    companyName: "Motherson",
    companyType: "MNC",
    designation: "Design Engineer",
    start: "Feb 2022",
    end: "Feb 2022",
    experienceInMonths: "1",
    responsibilities: "",
    type: "Full Time",
  },
  {
    domain: "Mechanical Engineering",
    companyName: "Simtek",
    companyType: "MNC",
    designation: "Application Engineer",
    start: "Mar 2022",
    end: "Mar 2022",
    experienceInMonths: "1",
    responsibilities: "",
    type: "Full Time",
  },
  {
    domain: "Information Technology",
    companyName: "Interviewdesk",
    companyType: "Start-up",
    designation: "Software Development Engineer",
    start: "Aug 2022",
    end: "Jan 2024",
    experienceInMonths: "18",
    responsibilities: "",
    type: "Full Time",
  },
  {
    domain: "Mechanical Engineering",
    companyName: "Tube Investments of India",
    companyType: "Indian Conglomerate",
    designation: "Project Engineer",
    start: "Jan 2024",
    end: "Present",
    experienceInMonths: "12",
    responsibilities: "",
    type: "Full Time",
  },
];
